"use client";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

// export const metadata: Metadata = {
//   title: {
//     default: "Next.js",
//     template: "%s | Next,js"
//   },
//   description: "Generated by create next app",
// };

const navLinks = [
  {
    name: "Register", 
    href: "/register"
  },
  {
    name: "Login",
    href: "/login"
  },
  {
    name: "Forgot Password",
    href: "/forgot-password"
  }
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ul>
          {navLinks?.map(link => {
            const isActive = pathName === link.href || (pathName.startsWith(link.href) && link.href !== "/");
            return  <li key={link.name} className={`${isActive ? 'font-bold' : 'font-normal'}`}>
            <Link href={link.href}>{link.name}</Link>
          </li>
          }
          )}
        </ul>
        <header>
            Header
        </header>
        {children}
        <footer>
          Footer
        </footer>
      </body>
    </html>
  );
}
